/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VipRouteImport } from './routes/vip'
import { Route as TechkidsRouteImport } from './routes/techkids'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as KidsIaRouteImport } from './routes/kids-ia'
import { Route as JovemProfissionalIaRouteImport } from './routes/jovem-profissional-ia'
import { Route as InovatechRouteImport } from './routes/inovatech'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuxiliarVeterinarioRouteImport } from './routes/auxiliar-veterinario'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const TechkidsRoute = TechkidsRouteImport.update({
  id: '/techkids',
  path: '/techkids',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsIaRoute = KidsIaRouteImport.update({
  id: '/kids-ia',
  path: '/kids-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const JovemProfissionalIaRoute = JovemProfissionalIaRouteImport.update({
  id: '/jovem-profissional-ia',
  path: '/jovem-profissional-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const InovatechRoute = InovatechRouteImport.update({
  id: '/inovatech',
  path: '/inovatech',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuxiliarVeterinarioRoute = AuxiliarVeterinarioRouteImport.update({
  id: '/auxiliar-veterinario',
  path: '/auxiliar-veterinario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auxiliar-veterinario': typeof AuxiliarVeterinarioRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/inovatech': typeof InovatechRoute
  '/jovem-profissional-ia': typeof JovemProfissionalIaRoute
  '/kids-ia': typeof KidsIaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/techkids': typeof TechkidsRoute
  '/vip': typeof VipRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auxiliar-veterinario': typeof AuxiliarVeterinarioRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/inovatech': typeof InovatechRoute
  '/jovem-profissional-ia': typeof JovemProfissionalIaRoute
  '/kids-ia': typeof KidsIaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/techkids': typeof TechkidsRoute
  '/vip': typeof VipRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auxiliar-veterinario': typeof AuxiliarVeterinarioRoute
  '/blog': typeof BlogRouteWithChildren
  '/contato': typeof ContatoRoute
  '/faq': typeof FaqRoute
  '/inovatech': typeof InovatechRoute
  '/jovem-profissional-ia': typeof JovemProfissionalIaRoute
  '/kids-ia': typeof KidsIaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/techkids': typeof TechkidsRoute
  '/vip': typeof VipRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auxiliar-veterinario'
    | '/blog'
    | '/contato'
    | '/faq'
    | '/inovatech'
    | '/jovem-profissional-ia'
    | '/kids-ia'
    | '/privacidade'
    | '/sobre'
    | '/techkids'
    | '/vip'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auxiliar-veterinario'
    | '/blog'
    | '/contato'
    | '/faq'
    | '/inovatech'
    | '/jovem-profissional-ia'
    | '/kids-ia'
    | '/privacidade'
    | '/sobre'
    | '/techkids'
    | '/vip'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/auxiliar-veterinario'
    | '/blog'
    | '/contato'
    | '/faq'
    | '/inovatech'
    | '/jovem-profissional-ia'
    | '/kids-ia'
    | '/privacidade'
    | '/sobre'
    | '/techkids'
    | '/vip'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuxiliarVeterinarioRoute: typeof AuxiliarVeterinarioRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  FaqRoute: typeof FaqRoute
  InovatechRoute: typeof InovatechRoute
  JovemProfissionalIaRoute: typeof JovemProfissionalIaRoute
  KidsIaRoute: typeof KidsIaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
  TechkidsRoute: typeof TechkidsRoute
  VipRoute: typeof VipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/techkids': {
      id: '/techkids'
      path: '/techkids'
      fullPath: '/techkids'
      preLoaderRoute: typeof TechkidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids-ia': {
      id: '/kids-ia'
      path: '/kids-ia'
      fullPath: '/kids-ia'
      preLoaderRoute: typeof KidsIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jovem-profissional-ia': {
      id: '/jovem-profissional-ia'
      path: '/jovem-profissional-ia'
      fullPath: '/jovem-profissional-ia'
      preLoaderRoute: typeof JovemProfissionalIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inovatech': {
      id: '/inovatech'
      path: '/inovatech'
      fullPath: '/inovatech'
      preLoaderRoute: typeof InovatechRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auxiliar-veterinario': {
      id: '/auxiliar-veterinario'
      path: '/auxiliar-veterinario'
      fullPath: '/auxiliar-veterinario'
      preLoaderRoute: typeof AuxiliarVeterinarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuxiliarVeterinarioRoute: AuxiliarVeterinarioRoute,
  BlogRoute: BlogRouteWithChildren,
  ContatoRoute: ContatoRoute,
  FaqRoute: FaqRoute,
  InovatechRoute: InovatechRoute,
  JovemProfissionalIaRoute: JovemProfissionalIaRoute,
  KidsIaRoute: KidsIaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
  TechkidsRoute: TechkidsRoute,
  VipRoute: VipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
